---
- name: Install RH-SSO on OpenShift
  hosts: localhost
  become: no
  tasks:
    - name: Create project namespace
      command: oc new-project sso
    - name: Run template install
      shell: |
        oc process -f ../rh-sso/sso73-x509-https.yaml \
        -p=APPLICATION_NAME={{ sso_application_name }} \
        -p=SSO_HOSTNAME={{ sso_hostname }} \
        -p=SSO_ADMIN_USERNAME={{ sso_admin_username }} \ 
        -p=SSO_ADMIN_PASSWORD={{ sso_admin_password }} \
        -p=SSO_REALM={{ sso_realm }} \
        | oc create -f-
